import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Student, Professor } from '@/types';

export type AuthRole = 'admin' | 'student' | 'professor' | null;

interface AuthUser {
  id: string;
  email: string;
  role: AuthRole;
  student?: Student;
  professor?: Professor;
}

interface AuthContextType {
  user: AuthUser | null;
  isAuthenticated: boolean;
  login: (email: string, password: string) => Promise<{ success: boolean; error?: string }>;
  signupAdmin: (email: string, password: string, name: string) => Promise<{ success: boolean; error?: string }>;
  signupStudent: (data: StudentSignupData) => Promise<{ success: boolean; error?: string }>;
  signupProfessor: (data: ProfessorSignupData) => Promise<{ success: boolean; error?: string }>;
  logout: () => void;
  validateAccessToken: (token: string) => boolean;
}

export interface StudentSignupData {
  email: string;
  password: string;
  name: string;
  nickname: string;
  bio: string;
  avatar: string;
  accessToken: string;
  level: 'A1' | 'A2' | 'B1' | 'B2';
}

export interface ProfessorSignupData {
  email: string;
  password: string;
  name: string;
  bio: string;
  avatar: string;
  languages: string[];
  specialization: string;
  accessToken: string;
}

// Mock valid access tokens (pre-generated by admin)
const validAccessTokens = ['STUDENT2024', 'LANG-ABC123', 'EDU-TOKEN-01', 'ACCESS-2024-XYZ'];
const validProfessorTokens = ['PROF2024', 'TEACHER-ABC', 'PROF-TOKEN-01'];

// Mock users database
const mockUsers: AuthUser[] = [
  {
    id: 'admin-1',
    email: 'admin@school.com',
    role: 'admin',
  },
  {
    id: 'prof-1',
    email: 'marie.dubois@example.com',
    role: 'professor',
    professor: {
      id: 'prof-1',
      name: 'Marie Dubois',
      email: 'marie.dubois@example.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marie',
      bio: 'Professeur de français avec 10 ans d\'expérience',
      languages: ['French', 'English', 'Spanish'],
      specialization: 'Conversation et grammaire',
      joinedAt: '2023-01-15',
      totalSessions: 156,
      rating: 4.8,
    },
  },
  {
    id: 'student-1',
    email: 'student@example.com',
    role: 'student',
    student: {
      id: '1',
      name: 'Sarah Johnson',
      email: 'student@example.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      nickname: 'Sarah',
      bio: 'Étudiante passionnée par les langues et les sciences',
      level: 'B1',
      joinedAt: '2024-01-10',
      skills: { pronunciation: 72, grammar: 68, vocabulary: 75, fluency: 65 },
      totalSessions: 12,
      hoursLearned: 18,
    },
  },
];

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | null>(() => {
    const saved = localStorage.getItem('auth_user');
    return saved ? JSON.parse(saved) : null;
  });

  const isAuthenticated = !!user;

  useEffect(() => {
    if (user) {
      localStorage.setItem('auth_user', JSON.stringify(user));
    } else {
      localStorage.removeItem('auth_user');
    }
  }, [user]);

  const validateAccessToken = (token: string): boolean => {
    return validAccessTokens.includes(token.toUpperCase().trim()) || 
           validProfessorTokens.includes(token.toUpperCase().trim());
  };

  const login = async (email: string, password: string): Promise<{ success: boolean; error?: string }> => {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Mock login - in real app, validate against backend
    const existingUser = mockUsers.find(u => u.email === email);
    if (existingUser) {
      setUser(existingUser);
      return { success: true };
    }
    
    // Check localStorage for registered users
    const registeredUsers = JSON.parse(localStorage.getItem('registered_users') || '[]');
    const foundUser = registeredUsers.find((u: AuthUser) => u.email === email);
    if (foundUser) {
      setUser(foundUser);
      return { success: true };
    }
    
    return { success: false, error: 'Email ou mot de passe incorrect' };
  };

  const signupAdmin = async (email: string, password: string, name: string): Promise<{ success: boolean; error?: string }> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Check if email already exists
    const registeredUsers = JSON.parse(localStorage.getItem('registered_users') || '[]');
    if (registeredUsers.find((u: AuthUser) => u.email === email) || mockUsers.find(u => u.email === email)) {
      return { success: false, error: 'Cet email est déjà utilisé' };
    }
    
    const newUser: AuthUser = {
      id: `admin-${Date.now()}`,
      email,
      role: 'admin',
    };
    
    registeredUsers.push(newUser);
    localStorage.setItem('registered_users', JSON.stringify(registeredUsers));
    
    return { success: true };
  };

  const signupStudent = async (data: StudentSignupData): Promise<{ success: boolean; error?: string }> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Validate access token
    if (!validAccessTokens.includes(data.accessToken.toUpperCase().trim())) {
      return { success: false, error: 'Token d\'accès invalide' };
    }
    
    // Check if email already exists
    const registeredUsers = JSON.parse(localStorage.getItem('registered_users') || '[]');
    if (registeredUsers.find((u: AuthUser) => u.email === data.email) || mockUsers.find(u => u.email === data.email)) {
      return { success: false, error: 'Cet email est déjà utilisé' };
    }
    
    const studentProfile: Student = {
      id: `student-${Date.now()}`,
      name: data.name,
      email: data.email,
      avatar: data.avatar,
      nickname: data.nickname,
      bio: data.bio,
      level: data.level,
      joinedAt: new Date().toISOString(),
      skills: { pronunciation: 20, grammar: 20, vocabulary: 20, fluency: 20 },
      totalSessions: 0,
      hoursLearned: 0,
    };
    
    const newUser: AuthUser = {
      id: studentProfile.id,
      email: data.email,
      role: 'student',
      student: studentProfile,
    };
    
    registeredUsers.push(newUser);
    localStorage.setItem('registered_users', JSON.stringify(registeredUsers));
    
    return { success: true };
  };

  const signupProfessor = async (data: ProfessorSignupData): Promise<{ success: boolean; error?: string }> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Validate access token
    if (!validProfessorTokens.includes(data.accessToken.toUpperCase().trim())) {
      return { success: false, error: 'Token d\'accès professeur invalide' };
    }
    
    // Check if email already exists
    const registeredUsers = JSON.parse(localStorage.getItem('registered_users') || '[]');
    if (registeredUsers.find((u: AuthUser) => u.email === data.email) || mockUsers.find(u => u.email === data.email)) {
      return { success: false, error: 'Cet email est déjà utilisé' };
    }
    
    const professorProfile: Professor = {
      id: `prof-${Date.now()}`,
      name: data.name,
      email: data.email,
      avatar: data.avatar,
      bio: data.bio,
      languages: data.languages,
      specialization: data.specialization,
      joinedAt: new Date().toISOString(),
      totalSessions: 0,
      rating: 0,
    };
    
    const newUser: AuthUser = {
      id: professorProfile.id,
      email: data.email,
      role: 'professor',
      professor: professorProfile,
    };
    
    registeredUsers.push(newUser);
    localStorage.setItem('registered_users', JSON.stringify(registeredUsers));
    
    return { success: true };
  };

  const logout = () => {
    setUser(null);
  };

  return (
    <AuthContext.Provider value={{ user, isAuthenticated, login, signupAdmin, signupStudent, signupProfessor, logout, validateAccessToken }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
