import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.rooms': 'Salles',
    'nav.students': 'Étudiants',
    'nav.sessions': 'Sessions',
    'nav.progress': 'Progression',
    'nav.profile': 'Profil',
    'nav.admin': 'Admin',
    'nav.student': 'Étudiant',
    'nav.lightMode': 'Mode clair',
    'nav.darkMode': 'Mode sombre',
    'nav.level': 'Niveau',
    'nav.logout': 'Déconnexion',
    'nav.quiz': 'Quiz',
    'nav.quizResults': 'Résultats Quiz',
    'nav.settings': 'Paramètres',
    'nav.summaries': 'Résumés',
    'nav.games': 'Jeux',
    
    // Auth
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.name': 'Nom complet',
    'auth.nickname': 'Pseudo',
    'auth.bio': 'Bio',
    'auth.level': 'Niveau',
    'auth.accessToken': "Token d'accès",
    'auth.createAccount': 'Créer un compte',
    'auth.loginButton': 'Se connecter',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.chooseRole': 'Choisissez votre type de compte',
    'auth.admin': 'Administrateur',
    'auth.student': 'Étudiant',
    'auth.adminDesc': 'Gérer les étudiants, salles et sessions',
    'auth.studentDesc': 'Rejoindre les sessions et suivre vos progrès',
    'auth.chooseAvatar': 'Choisissez votre avatar',
    'auth.selectImage': 'Sélectionnez une image qui vous représente',
    'auth.yourInfo': 'Vos informations',
    'auth.completeProfile': 'Complétez votre profil',
    'auth.currentLevel': 'Votre niveau actuel',
    'auth.bioPlaceholder': "Parlez-nous de vous et de vos objectifs d'apprentissage...",
    'auth.tokenTitle': "Token d'accès",
    'auth.tokenDesc': "Entrez le token d'accès fourni par votre administrateur",
    'auth.noToken': "Si vous n'avez pas de token, contactez votre administrateur",
    'auth.back': 'Retour',
    'auth.continue': 'Continuer',
    'auth.loading': 'Chargement...',
    'auth.creating': 'Création...',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.signupSuccess': 'Compte créé avec succès ! Connectez-vous maintenant.',
    'auth.allRightsReserved': 'Tous droits réservés',
    
    // Admin Students
    'students.title': 'Étudiants',
    'students.subtitle': 'Gérer et visualiser tous les étudiants inscrits',
    'students.search': 'Rechercher des étudiants...',
    'students.allLevels': 'Tous les niveaux',
    'students.noResults': 'Aucun étudiant trouvé',
    'students.noResultsHint': "Essayez d'ajuster votre recherche ou vos filtres",
    'students.sessionsCompleted': 'sessions',
    'students.progress': 'Progression',
    
    // Admin Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bienvenue !',
    'dashboard.welcomeDesc': "Voici ce qui se passe dans votre école de langues.",
    'dashboard.totalStudents': 'Total étudiants',
    'dashboard.activeRooms': 'Salles actives',
    'dashboard.scheduledSessions': 'Sessions planifiées',
    'dashboard.completedSessions': 'Sessions terminées',
    'dashboard.upcomingSessions': 'Sessions à venir',
    'dashboard.liveSessions': 'Sessions en direct',
    'dashboard.liveRooms': 'Salles en direct',
    'dashboard.recentStudents': 'Étudiants récents',
    'dashboard.viewAll': 'Voir tout',
    'dashboard.noLiveRooms': 'Aucune salle active pour le moment',
    'dashboard.thisMonth': 'Ce mois',
    'dashboard.liveNow': 'En direct',
    'dashboard.thisWeek': 'Cette semaine',
    'dashboard.allTime': 'Tout le temps',
    'dashboard.quizResults': 'Résultats des Quiz',
    'dashboard.noQuizResults': 'Aucun résultat de quiz disponible',
    
    // Student Dashboard
    'student.welcome': 'Bon retour',
    'student.welcomeDesc': "Vous faites d'excellents progrès ! Continuez votre apprentissage.",
    'student.yourLevel': 'Votre niveau',
    'student.currentLevel': 'Niveau actuel',
    'student.hoursLearned': 'Heures apprises',
    'student.sessionsCompleted': 'Sessions terminées',
    'student.liveNow': 'En direct maintenant',
    'student.joinNow': 'Rejoindre',
    'student.upcomingSessions': 'Sessions à venir',
    'student.yourProgress': 'Votre progression',
    'student.skillProgress': 'Progression des compétences',
    'student.viewDetails': 'Voir détails',
    'student.noUpcoming': 'Aucune session planifiée',
    'student.sessionInProgress': 'Session en cours !',
    'student.happeningNow': 'se déroule maintenant',
    'student.overallProgress': 'Progression globale',
    'student.studyStreak': 'Série d\'étude',
    'student.days': 'jours',
    
    // Profile
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérer les paramètres de votre compte et vos préférences',
    'profile.edit': 'Modifier le profil',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.nickname': 'Pseudo',
    'profile.bio': 'Bio',
    'profile.noBio': 'Pas de bio encore',
    'profile.sessions': 'Sessions',
    'profile.hours': 'Heures',
    'profile.streak': 'Série',
    'profile.accountInfo': 'Informations du compte',
    'profile.memberSince': 'Membre depuis',
    'profile.currentLevel': 'Niveau actuel',
    'profile.accountStatus': 'Statut du compte',
    'profile.active': 'Actif',
    'profile.updated': 'Profil mis à jour avec succès !',
    
    // Quiz
    'quiz.title': 'Quiz',
    'quiz.subtitle': 'Testez vos connaissances et suivez vos résultats',
    'quiz.available': 'Quiz disponibles',
    'quiz.history': 'Historique des quiz',
    'quiz.questions': 'questions',
    'quiz.start': 'Commencer',
    'quiz.passed': 'Réussi',
    'quiz.failed': 'Échoué',
    'quiz.noHistory': "Vous n'avez pas encore passé de quiz",
    'quiz.question': 'Question',
    'quiz.of': 'sur',
    'quiz.next': 'Suivant',
    'quiz.submit': 'Terminer',
    'quiz.results': 'Résultats',
    'quiz.score': 'Score',
    'quiz.close': 'Fermer',
    'quiz.pending': 'En attente',
    'quiz.completed': 'Terminé',
    'quiz.session': 'Session',
    'quiz.date': 'Date',
    'quiz.student': 'Étudiant',
    
    // Rooms
    'rooms.title': 'Gestion des salles',
    'rooms.subtitle': 'Créer et gérer vos salles d\'apprentissage des langues',
    'rooms.create': 'Créer une salle',
    'rooms.createNew': 'Créer une nouvelle salle',
    'rooms.live': 'En direct',
    'rooms.capacity': 'Capacité',
    'rooms.join': 'Rejoindre',
    'rooms.search': 'Rechercher des salles...',
    'rooms.allStatus': 'Tous les statuts',
    'rooms.noRooms': 'Aucune salle trouvée',
    'rooms.noRoomsHint': 'Créez votre première salle pour commencer',
    'rooms.adjustFilters': 'Essayez d\'ajuster vos filtres',
    'rooms.name': 'Nom de la salle',
    'rooms.namePlaceholder': 'ex: Club de conversation espagnol',
    'rooms.language': 'Langue',
    'rooms.selectLanguage': 'Sélectionner une langue',
    'rooms.level': 'Niveau',
    'rooms.selectLevel': 'Sélectionner un niveau',
    'rooms.duration': 'Durée (minutes)',
    'rooms.selectDuration': 'Sélectionner la durée',
    'rooms.dateTime': 'Date et heure',
    'rooms.maxStudents': 'Étudiants max',
    'rooms.objective': 'Objectif de la session',
    'rooms.objectivePlaceholder': 'Décrivez ce que les étudiants vont apprendre ou pratiquer...',
    'rooms.inviteStudents': 'Inviter des étudiants',
    'rooms.studentsSelected': 'étudiant(s) sélectionné(s)',
    'rooms.startsIn': 'Commence dans',
    
    // Sessions
    'sessions.title': 'Mes Sessions',
    'sessions.subtitle': 'Voir et rejoindre vos sessions d\'apprentissage assignées',
    'sessions.upcoming': 'À venir',
    'sessions.past': 'Passées',
    'sessions.duration': 'Durée',
    'sessions.startIn': 'Commence dans',
    'sessions.allSessions': 'Toutes les sessions',
    'sessions.noSessions': 'Aucune session trouvée',
    'sessions.changeFilter': 'Essayez de changer le filtre',
    'sessions.noAssigned': 'Vous n\'avez pas encore de sessions assignées',
    'sessions.viewDetails': 'Voir détails',
    'sessions.viewSummary': 'Voir résumé',
    
    // Progress
    'progress.title': 'Progression et Niveau',
    'progress.subtitle': 'Suivez votre parcours d\'apprentissage des langues',
    'progress.overallProgress': 'Progression globale',
    'progress.progressTo': 'Progression vers',
    'progress.keepPracticing': 'Continuez à pratiquer ! Il vous faut',
    'progress.morePoints': 'points de plus pour atteindre',
    'progress.levelPath': 'Parcours des niveaux CECR',
    'progress.skillBreakdown': 'Détail des compétences',
    'progress.pronunciation': 'Prononciation',
    'progress.pronunciationDesc': 'Votre capacité à produire des sons avec précision',
    'progress.grammar': 'Grammaire',
    'progress.grammarDesc': 'Compréhension et utilisation des règles linguistiques',
    'progress.vocabulary': 'Vocabulaire',
    'progress.vocabularyDesc': 'Connaissance des mots et de leurs significations',
    'progress.fluency': 'Aisance',
    'progress.fluencyDesc': 'Fluidité et naturel de la parole',
    'progress.achievements': 'Réalisations récentes',
    'progress.firstSession': 'Première session',
    'progress.firstSessionDesc': 'Terminé votre première session d\'apprentissage',
    'progress.streak7': 'Série de 7 jours',
    'progress.streak7Desc': 'Pratiqué pendant 7 jours consécutifs',
    'progress.convoPro': 'Pro de la conversation',
    'progress.convoProDesc': 'Participé à 10 conversations',
    'progress.vocabBuilder': 'Constructeur de vocabulaire',
    'progress.vocabBuilderDesc': 'Appris 100 nouveaux mots',
    'progress.levelUp': 'Niveau supérieur !',
    'progress.levelUpDesc': 'Atteint le niveau B1',
    'progress.topStudent': 'Meilleur étudiant',
    'progress.topStudentDesc': 'Classé dans le top 10% ce mois',
    
    // Levels
    'level.beginner': 'Débutant',
    'level.beginnerDesc': 'Peut comprendre des phrases et expressions de base',
    'level.elementary': 'Élémentaire',
    'level.elementaryDesc': 'Peut communiquer dans des tâches simples et routinières',
    'level.intermediate': 'Intermédiaire',
    'level.intermediateDesc': 'Peut gérer la plupart des situations de voyage',
    'level.upperIntermediate': 'Intermédiaire supérieur',
    'level.upperIntermediateDesc': 'Peut interagir avec aisance avec des locuteurs natifs',
    'level.advanced': 'Avancé',
    'level.advancedDesc': 'Peut s\'exprimer avec aisance et spontanéité',
    'level.mastery': 'Maîtrise',
    'level.masteryDesc': 'Peut comprendre pratiquement tout ce qui est lu ou entendu',
    
    // Quiz Results (Admin)
    'quizResults.subtitle': 'Visualiser les résultats des quiz de tous les étudiants',
    'quizResults.totalQuizzes': 'Total quiz passés',
    'quizResults.passedQuizzes': 'Quiz réussis',
    'quizResults.avgScore': 'Score moyen',
    'quizResults.average': 'Moyenne générale',
    'quizResults.search': 'Rechercher par étudiant ou quiz...',
    'quizResults.allResults': 'Tous les résultats',
    
    // Common
    'common.join': 'Rejoindre',
    'common.view': 'Voir',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.live': 'En direct',
    'common.scheduled': 'Planifié',
    'common.completed': 'Terminé',
    'common.students': 'étudiants',
    'common.hours': 'heures',
    'common.minutes': 'minutes',
    'common.today': "Aujourd'hui",
    'common.tomorrow': 'Demain',
    'common.yesterday': 'Hier',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.rooms': 'الغرف',
    'nav.students': 'الطلاب',
    'nav.sessions': 'الجلسات',
    'nav.progress': 'التقدم',
    'nav.profile': 'الملف الشخصي',
    'nav.admin': 'مشرف',
    'nav.student': 'طالب',
    'nav.lightMode': 'الوضع الفاتح',
    'nav.darkMode': 'الوضع الداكن',
    'nav.level': 'المستوى',
    'nav.logout': 'تسجيل الخروج',
    'nav.quiz': 'اختبار',
    'nav.quizResults': 'نتائج الاختبارات',
    'nav.settings': 'الإعدادات',
    'nav.summaries': 'الملخصات',
    'nav.games': 'ألعاب',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم الكامل',
    'auth.nickname': 'اسم المستخدم',
    'auth.bio': 'نبذة عنك',
    'auth.level': 'المستوى',
    'auth.accessToken': 'رمز الوصول',
    'auth.createAccount': 'إنشاء الحساب',
    'auth.loginButton': 'تسجيل الدخول',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.chooseRole': 'اختر نوع حسابك',
    'auth.admin': 'مشرف',
    'auth.student': 'طالب',
    'auth.adminDesc': 'إدارة الطلاب والغرف والجلسات',
    'auth.studentDesc': 'الانضمام إلى الجلسات وتتبع تقدمك',
    'auth.chooseAvatar': 'اختر صورتك الرمزية',
    'auth.selectImage': 'اختر صورة تمثلك',
    'auth.yourInfo': 'معلوماتك الشخصية',
    'auth.completeProfile': 'أكمل ملفك الشخصي',
    'auth.currentLevel': 'مستواك الحالي',
    'auth.bioPlaceholder': 'أخبرنا عن نفسك وأهداف التعلم الخاصة بك...',
    'auth.tokenTitle': 'رمز الوصول',
    'auth.tokenDesc': 'أدخل رمز الوصول الذي قدمه لك المشرف',
    'auth.noToken': 'إذا لم يكن لديك رمز، اتصل بمشرفك',
    'auth.back': 'رجوع',
    'auth.continue': 'التالي',
    'auth.loading': 'جاري التحميل...',
    'auth.creating': 'جاري الإنشاء...',
    'auth.backToLogin': 'العودة لتسجيل الدخول',
    'auth.signupSuccess': 'تم إنشاء الحساب بنجاح! سجل دخولك الآن.',
    'auth.allRightsReserved': 'جميع الحقوق محفوظة',
    
    // Admin Students
    'students.title': 'الطلاب',
    'students.subtitle': 'إدارة وعرض جميع الطلاب المسجلين',
    'students.search': 'البحث عن الطلاب...',
    'students.allLevels': 'جميع المستويات',
    'students.noResults': 'لم يتم العثور على طلاب',
    'students.noResultsHint': 'حاول تعديل البحث أو الفلاتر',
    'students.sessionsCompleted': 'جلسات',
    'students.progress': 'التقدم',
    
    // Admin Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً!',
    'dashboard.welcomeDesc': 'إليك ما يحدث في مدرستك للغات.',
    'dashboard.totalStudents': 'إجمالي الطلاب',
    'dashboard.activeRooms': 'الغرف النشطة',
    'dashboard.scheduledSessions': 'الجلسات المجدولة',
    'dashboard.completedSessions': 'الجلسات المكتملة',
    'dashboard.upcomingSessions': 'الجلسات القادمة',
    'dashboard.liveSessions': 'الجلسات المباشرة',
    'dashboard.liveRooms': 'الغرف المباشرة',
    'dashboard.recentStudents': 'الطلاب الجدد',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.noLiveRooms': 'لا توجد غرف نشطة حالياً',
    'dashboard.thisMonth': 'هذا الشهر',
    'dashboard.liveNow': 'مباشر الآن',
    'dashboard.thisWeek': 'هذا الأسبوع',
    'dashboard.allTime': 'كل الوقت',
    'dashboard.quizResults': 'نتائج الاختبارات',
    'dashboard.noQuizResults': 'لا توجد نتائج اختبارات متاحة',
    
    // Student Dashboard
    'student.welcome': 'مرحباً بعودتك',
    'student.welcomeDesc': 'أنت تحرز تقدماً رائعاً! واصل التعلم.',
    'student.yourLevel': 'مستواك',
    'student.currentLevel': 'المستوى الحالي',
    'student.hoursLearned': 'ساعات التعلم',
    'student.sessionsCompleted': 'الجلسات المكتملة',
    'student.liveNow': 'مباشر الآن',
    'student.joinNow': 'انضم الآن',
    'student.upcomingSessions': 'الجلسات القادمة',
    'student.yourProgress': 'تقدمك',
    'student.skillProgress': 'تقدم المهارات',
    'student.viewDetails': 'عرض التفاصيل',
    'student.noUpcoming': 'لا توجد جلسات مجدولة',
    'student.sessionInProgress': 'جلسة جارية!',
    'student.happeningNow': 'تجري الآن',
    'student.overallProgress': 'التقدم الإجمالي',
    'student.studyStreak': 'سلسلة الدراسة',
    'student.days': 'أيام',
    
    // Profile
    'profile.title': 'ملفي الشخصي',
    'profile.subtitle': 'إدارة إعدادات حسابك وتفضيلاتك',
    'profile.edit': 'تعديل الملف',
    'profile.save': 'حفظ',
    'profile.cancel': 'إلغاء',
    'profile.nickname': 'اسم المستخدم',
    'profile.bio': 'نبذة عنك',
    'profile.noBio': 'لا توجد نبذة بعد',
    'profile.sessions': 'جلسات',
    'profile.hours': 'ساعات',
    'profile.streak': 'تتابع',
    'profile.accountInfo': 'معلومات الحساب',
    'profile.memberSince': 'عضو منذ',
    'profile.currentLevel': 'المستوى الحالي',
    'profile.accountStatus': 'حالة الحساب',
    'profile.active': 'نشط',
    'profile.updated': 'تم تحديث الملف الشخصي بنجاح!',
    
    // Quiz
    'quiz.title': 'الاختبار',
    'quiz.subtitle': 'اختبر معرفتك وتابع نتائجك',
    'quiz.available': 'الاختبارات المتاحة',
    'quiz.history': 'سجل الاختبارات',
    'quiz.questions': 'أسئلة',
    'quiz.start': 'ابدأ',
    'quiz.passed': 'ناجح',
    'quiz.failed': 'راسب',
    'quiz.noHistory': 'لم تخض أي اختبار بعد',
    'quiz.question': 'السؤال',
    'quiz.of': 'من',
    'quiz.next': 'التالي',
    'quiz.submit': 'إنهاء',
    'quiz.results': 'النتائج',
    'quiz.score': 'النتيجة',
    'quiz.close': 'إغلاق',
    'quiz.pending': 'قيد الانتظار',
    'quiz.completed': 'مكتمل',
    'quiz.session': 'الجلسة',
    'quiz.date': 'التاريخ',
    'quiz.student': 'الطالب',
    
    // Quiz Results (Admin)
    'quizResults.subtitle': 'عرض نتائج اختبارات جميع الطلاب',
    'quizResults.totalQuizzes': 'إجمالي الاختبارات',
    'quizResults.passedQuizzes': 'الاختبارات الناجحة',
    'quizResults.avgScore': 'متوسط النتيجة',
    'quizResults.average': 'المتوسط العام',
    'quizResults.search': 'البحث عن طالب أو اختبار...',
    'quizResults.allResults': 'جميع النتائج',
    
    // Rooms
    'rooms.title': 'إدارة الغرف',
    'rooms.subtitle': 'إنشاء وإدارة غرف تعلم اللغات الخاصة بك',
    'rooms.create': 'إنشاء غرفة',
    'rooms.createNew': 'إنشاء غرفة جديدة',
    'rooms.live': 'مباشر',
    'rooms.capacity': 'السعة',
    'rooms.join': 'انضم',
    'rooms.search': 'البحث عن الغرف...',
    'rooms.allStatus': 'جميع الحالات',
    'rooms.noRooms': 'لم يتم العثور على غرف',
    'rooms.noRoomsHint': 'أنشئ غرفتك الأولى للبدء',
    'rooms.adjustFilters': 'حاول تعديل الفلاتر',
    'rooms.name': 'اسم الغرفة',
    'rooms.namePlaceholder': 'مثال: نادي المحادثة الإسبانية',
    'rooms.language': 'اللغة',
    'rooms.selectLanguage': 'اختر لغة',
    'rooms.level': 'المستوى',
    'rooms.selectLevel': 'اختر مستوى',
    'rooms.duration': 'المدة (دقائق)',
    'rooms.selectDuration': 'اختر المدة',
    'rooms.dateTime': 'التاريخ والوقت',
    'rooms.maxStudents': 'الحد الأقصى للطلاب',
    'rooms.objective': 'هدف الجلسة',
    'rooms.objectivePlaceholder': 'صف ما سيتعلمه أو يمارسه الطلاب...',
    'rooms.inviteStudents': 'دعوة الطلاب',
    'rooms.studentsSelected': 'طالب(طلاب) محدد',
    'rooms.startsIn': 'تبدأ في',
    
    // Sessions
    'sessions.title': 'جلساتي',
    'sessions.subtitle': 'عرض والانضمام إلى جلسات التعلم المخصصة لك',
    'sessions.upcoming': 'القادمة',
    'sessions.past': 'السابقة',
    'sessions.duration': 'المدة',
    'sessions.startIn': 'تبدأ في',
    'sessions.allSessions': 'جميع الجلسات',
    'sessions.noSessions': 'لم يتم العثور على جلسات',
    'sessions.changeFilter': 'حاول تغيير الفلتر',
    'sessions.noAssigned': 'ليس لديك جلسات مخصصة بعد',
    'sessions.viewDetails': 'عرض التفاصيل',
    'sessions.viewSummary': 'عرض الملخص',
    
    // Progress
    'progress.title': 'التقدم والمستوى',
    'progress.subtitle': 'تتبع رحلة تعلم اللغة الخاصة بك',
    'progress.overallProgress': 'التقدم الإجمالي',
    'progress.progressTo': 'التقدم نحو',
    'progress.keepPracticing': 'استمر في التدريب! تحتاج إلى',
    'progress.morePoints': 'نقاط إضافية للوصول إلى',
    'progress.levelPath': 'مسار مستويات CEFR',
    'progress.skillBreakdown': 'تفصيل المهارات',
    'progress.pronunciation': 'النطق',
    'progress.pronunciationDesc': 'قدرتك على إنتاج الأصوات بدقة',
    'progress.grammar': 'القواعد',
    'progress.grammarDesc': 'فهم واستخدام القواعد اللغوية',
    'progress.vocabulary': 'المفردات',
    'progress.vocabularyDesc': 'معرفة الكلمات ومعانيها',
    'progress.fluency': 'الطلاقة',
    'progress.fluencyDesc': 'سلاسة وانسياب الكلام',
    'progress.achievements': 'الإنجازات الأخيرة',
    'progress.firstSession': 'الجلسة الأولى',
    'progress.firstSessionDesc': 'أكملت جلستك التعليمية الأولى',
    'progress.streak7': 'سلسلة 7 أيام',
    'progress.streak7Desc': 'تدربت لمدة 7 أيام متتالية',
    'progress.convoPro': 'محترف المحادثة',
    'progress.convoProDesc': 'شاركت في 10 محادثات',
    'progress.vocabBuilder': 'بناء المفردات',
    'progress.vocabBuilderDesc': 'تعلمت 100 كلمة جديدة',
    'progress.levelUp': 'ارتقيت!',
    'progress.levelUpDesc': 'وصلت إلى مستوى B1',
    'progress.topStudent': 'أفضل طالب',
    'progress.topStudentDesc': 'في أفضل 10% هذا الشهر',
    
    // Levels
    'level.beginner': 'مبتدئ',
    'level.beginnerDesc': 'يمكنه فهم العبارات والتعبيرات الأساسية',
    'level.elementary': 'ابتدائي',
    'level.elementaryDesc': 'يمكنه التواصل في المهام البسيطة والروتينية',
    'level.intermediate': 'متوسط',
    'level.intermediateDesc': 'يمكنه التعامل مع معظم مواقف السفر',
    'level.upperIntermediate': 'فوق المتوسط',
    'level.upperIntermediateDesc': 'يمكنه التفاعل بطلاقة مع الناطقين الأصليين',
    'level.advanced': 'متقدم',
    'level.advancedDesc': 'يمكنه التعبير عن الأفكار بطلاقة وتلقائية',
    'level.mastery': 'إتقان',
    'level.masteryDesc': 'يمكنه فهم كل ما يُقرأ أو يُسمع تقريباً',
    
    // Common
    'common.join': 'انضم',
    'common.view': 'عرض',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.live': 'مباشر',
    'common.scheduled': 'مجدول',
    'common.completed': 'مكتمل',
    'common.students': 'طلاب',
    'common.hours': 'ساعات',
    'common.minutes': 'دقائق',
    'common.today': 'اليوم',
    'common.tomorrow': 'غداً',
    'common.yesterday': 'أمس',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
